---
- hosts: me
  remote_user: root
  tasks:

  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
    become: yes

  - name: Enable Docker Edge repo
    ini_file:
      dest: /etc/yum.repos.d/docer-ce.repo
      section: 'docker-ce-edge'
      option: enabled
      value: 0
    become: yes
    
  - name: Install Docker
    become: true
    yum: 
      name: docker-ce
      state: latest
      update_cache: yes

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes
    become: yes
            
  - name: Check if container is running
    shell: docker ps
    become: yes